-- Directus Schema untuk APM Portal
-- Jalankan di Directus admin atau via migration

-- =============================================
-- Collection: apm_tips (Tips & Strategi)
-- =============================================
-- Fields:
-- id (integer, primary key, auto increment)
-- status (string) - draft/published
-- judul (string) - Title
-- deskripsi (text) - Description
-- icon (string) - lightbulb/target/search/users/clock/mic/message-circle
-- urutan (integer) - Display order

-- =============================================
-- Collection: apm_templates (Template Proposal)
-- =============================================
-- Fields:
-- id (integer, primary key, auto increment)
-- status (string) - draft/published
-- judul (string) - Title
-- deskripsi (text) - Description
-- format (string) - DOCX/PDF/PPTX/ZIP
-- kategori (string) - proposal/presentation/design
-- file (file) - Uploaded file
-- urutan (integer) - Display order

-- =============================================
-- Collection: apm_faq (FAQ)
-- =============================================
-- Fields:
-- id (integer, primary key, auto increment)
-- status (string) - draft/published
-- pertanyaan (string) - Question
-- jawaban (text) - Answer
-- urutan (integer) - Display order

-- =============================================
-- Collection: apm_panduan (Panduan Pendaftaran)
-- =============================================
-- Fields:
-- id (integer, primary key, auto increment)
-- status (string) - draft/published
-- tipe (string) - pendaftaran/expo
-- step (integer) - Step number
-- judul (string) - Step title
-- deskripsi (text) - Step description
-- urutan (integer) - Display order

-- =============================================
-- Collection: apm_downloads (Download Materi)
-- =============================================
-- Fields:
-- id (integer, primary key, auto increment)
-- status (string) - draft/published
-- judul (string) - Title
-- deskripsi (text) - Description
-- format (string) - PDF/PPTX/ZIP/MP4
-- ukuran (string) - File size (e.g., "2.5 MB")
-- kategori (string) - panduan/materi/template/video/contoh
-- file (file) - Uploaded file
-- date_created (datetime)

-- =============================================
-- Tambahan fields untuk apm_expo (existing)
-- =============================================
-- jumlah_pengunjung (integer) - Visitor count
-- jumlah_proyek (integer) - Number of projects displayed
-- rating (float) - Average rating
